modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MrCrayfish/Filters/issues"

[[mods]]
modId="filters"
version="1.1.2"
displayName="Filters"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/filters/update.json"
displayURL="https://mrcrayfish.com"
logoFile="filters.png"
credits=""
authors="MrCrayfish"
description='''
A mod that improves the Creative GUI by introducing filters based on tags
'''

[[dependencies.filters]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.filters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
