modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Krxwallo/FiltersReborn/issues"
license="GPLv3+"

[[mods]]
modId="filters"
version="1.1.2"
displayName="Filters"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/filters/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/filters-reborn"
logoFile="filters_reborn_icon.png"
credits=""
authors="MrCrayfish & justAm0dd3r"
description='''
A continuation of the filters mod originally by MrCrayfish.
This mod adds nice item filters to the creative tab so that you can find your items/groups of items(e.g. spawn eggs or
 colored glass) much easier.
'''

[[dependencies.filters]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.filters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17, 1.18)"
    ordering="NONE"
    side="BOTH"
